# Generated by Django 3.1.3 on 2020-11-25 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0003_list'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='List',
            new_name='Todo',
        ),
    ]
