# Generated by Django 3.1.3 on 2020-11-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0004_auto_20201125_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='Description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
